// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsrZcPaky4y32ZajKiDy3HcfAvYCk3fjQ',
    appId: '1:489884048194:web:39100a5a8c884c3abc06db',
    messagingSenderId: '489884048194',
    projectId: 'auto-feed-29ce5',
    authDomain: 'auto-feed-29ce5.firebaseapp.com',
    databaseURL: 'https://auto-feed-29ce5-default-rtdb.firebaseio.com',
    storageBucket: 'auto-feed-29ce5.firebasestorage.app',
    measurementId: 'G-DW8H3FEC3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Z9HugRaIkrBiIrnBnrMoVfMF3-XHedA',
    appId: '1:489884048194:android:df7e6f6ed8999185bc06db',
    messagingSenderId: '489884048194',
    projectId: 'auto-feed-29ce5',
    databaseURL: 'https://auto-feed-29ce5-default-rtdb.firebaseio.com',
    storageBucket: 'auto-feed-29ce5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Nuw4n3g68dcTSwEU6UmTAz4oN74N87c',
    appId: '1:489884048194:ios:f05b2447c235acf7bc06db',
    messagingSenderId: '489884048194',
    projectId: 'auto-feed-29ce5',
    databaseURL: 'https://auto-feed-29ce5-default-rtdb.firebaseio.com',
    storageBucket: 'auto-feed-29ce5.firebasestorage.app',
    iosBundleId: 'com.example.autoFeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Nuw4n3g68dcTSwEU6UmTAz4oN74N87c',
    appId: '1:489884048194:ios:f05b2447c235acf7bc06db',
    messagingSenderId: '489884048194',
    projectId: 'auto-feed-29ce5',
    databaseURL: 'https://auto-feed-29ce5-default-rtdb.firebaseio.com',
    storageBucket: 'auto-feed-29ce5.firebasestorage.app',
    iosBundleId: 'com.example.autoFeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsrZcPaky4y32ZajKiDy3HcfAvYCk3fjQ',
    appId: '1:489884048194:web:6ed98a51f81da52cbc06db',
    messagingSenderId: '489884048194',
    projectId: 'auto-feed-29ce5',
    authDomain: 'auto-feed-29ce5.firebaseapp.com',
    databaseURL: 'https://auto-feed-29ce5-default-rtdb.firebaseio.com',
    storageBucket: 'auto-feed-29ce5.firebasestorage.app',
    measurementId: 'G-F96H0R45BV',
  );
}
